#!/bin/bash


export IP_DB=localhost
export FRAGNOSTIC_DAO_JDBCIMPL_MYSQL_CONF_FILE=fragnostic-dao-jdbc-mysql-impl/src/test/resources/fragnostic-dao-mysql8-datasource-test.properties


./sbt -v -213 -Dsbt.io.implicit.relative.glob.conversion=allow
