#!/bin/bash

export IP_DB=localhost
echo "      IP_DB : $IP_DB"

export IP_HOST=localhost
echo "    IP_HOST : $IP_HOST"
echo ""

ant -f ./fragnostic-dao-jdbc-mysql-impl/src/test/resources/afterall/build-afterall.xml afterall

