#!/bin/bash

export IP_DB=localhost
echo "      IP_DB : $IP_DB"

export IP_HOST=localhost
echo "    IP_HOST : $IP_HOST"
echo ""

ant -f ./fragnostic-dao-jdbcimpl-mysql/src/test/resources/beforeall/build-beforeall.xml beforeall
